### PR TITLE
Added a fix to work with the "termguicolors" option

### LINKED ISSUE #60: Support for termguicolors option
Hi,
thanks for the nice project! I recently switched to true colors in terminal vim. Unfortunately, semantic-highlight only checks for the older `guicolors` option and not for `termguicolors` that is now part of the official vim release.

### PR DESCRIPTION
**Pull request by IngoHeimbach**
Fixes #60

### CODE REVIEW

**Comment by supercrabtree** [comment]
👍

**Comment by barlik** [comment]
tested, works for me!

**Comment by zhuochun** [comment]
tested and works perfectly.

**Comment by balta2ar** [comment]
@jaxbot Could you please merge this?

**Comment by Mephistophiles** [comment]
+1, this pull request fixed bug with termguicolors. Merge please

**Pull request merged**
