### PR TITLE
Add C preprocessor keywords to the blacklist

### PR DESCRIPTION
**Pull request by 1ace**

### CODE REVIEW

**Comment by faceleg** [comment]
LGTM @jaxbot

**Comment by faceleg** [comment]
Thanks :dancer:

**Comment by 1ace** [comment]
I just realized I forgot `#ifndef`… I can't make a pull request right now, but you can also just add this yourself.
I'll make a pull request this weekend if you don't beat me to it :)

**Comment by faceleg** [comment]
You will beat me :dancer: 

Mainly I don't use C.

**Pull request merged**
